# // █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# // ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

### --- WINDOW RULES --- ###

# Video & Browser Inhibit
windowrule {
    name = idle-inhibit-media
    match:class = ^(.*celluloid.*|mpv|vlc|LibreWolf|floorp|brave-browser|firefox|chromium|zen|vivaldi|[Ss]potify)$
    idle_inhibit = fullscreen
}

# Picture-in-Picture logic
windowrule {
    name = pip-behavior
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    
    tag = +pip
    float = on
    keep_aspect_ratio = on
    pin = on
    move = (monitor_w*0.72) (monitor_h*0.72)
    size = (monitor_w*0.25) (monitor_h*0.25)
}

# High Opacity Browsers
windowrule {
    name = browser-opacity
    match:class = ^(firefox|brave-browser)$
    opacity = 0.90 0.90 1.0
}

# Standard Dev & Terminal Opacity
windowrule {
    name = dev-tools-opacity
    match:class = ^(code-oss|[Cc]ode|code-url-handler|code-insiders-url-handler|kitty)$
    opacity = 0.80 0.80 1.0
}

# System & File Managers
windowrule {
    name = system-tools-opacity
    match:class = ^(org.kde.dolphin|org.kde.ark|nwg-look|qt5ct|qt6ct|kvantummanager)$
    opacity = 0.80 0.80 1.0
}

# Networking & Audio
windowrule {
    name = network-audio-opacity
    match:class = ^(org.pulseaudio.pavucontrol|blueman-manager|nm-applet|nm-connection-editor)$
    opacity = 0.80 0.70 1.0
}

# Polkit & Portals
windowrule {
    name = portal-opacity
    match:class = ^(org.kde.polkit-.*|polkit-gnome-.*|org.freedesktop.impl.portal.*)$
    opacity = 0.80 0.70 1.0
}

# Game Launchers & Music
windowrule {
    name = social-media-opacity
    match:class = ^([Ss]team|steamwebhelper|[Ss]potify)$
    match:initial_title = ^(Spotify.*)$
    opacity = 0.70 0.70 1.0
}

# Floating Apps & Misc Opacity
windowrule {
    name = floating-apps
    match:class = ^(Signal|com.github.rafostar.Clapper|app.drey.Warp|net.davidotek.pupgui2|yad|eog|io.github.alainm23.planify|io.gitlab.theevilskeleton.Upscaler|com.github.unrud.VideoDownloader|io.gitlab.adhami3310.Impression|io.missioncenter.MissionCenter|io.github.flattool.Warehouse|com.github.tchx84.Flatseal|hu.kramo.Cartridges|com.obsproject.Studio|gnome-boxes|vesktop|discord|WebCord|ArmCord)$
    
    float = on
    opacity = 0.80 0.80 1.0
}

# Jetbrains Fix
windowrule {
    name = jetbrains-focus-fix
    match:class = ^(.*jetbrains.*)$
    match:title = ^(win[0-9]+)$
    no_initial_focus = on
}

### --- LAYER RULES --- ###

# // █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# // █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule {
    name = panel-blur
    match:namespace = ^(rofi|notifications|swaync-notification-window|swaync-control-center|logout_dialog)$
    
    blur = on
    ignore_alpha = 0.5
}
